name: CI_IBM

on: [push]

jobs:
  build:
    runs-on: image: maven:3.8.6-openjdk-18
    steps:
      - name: Rodando um script shell
        run: mvn package -Dmaven.test.skip
  teste:
    runs-on: image: maven:3.8.6-openjdk-18
    steps:
      - name: Rodando um script shell
        run: mvn test